services:
    tee:
        image: morphicnetwork/morphic-agent:latest
        container_name: morphic-agent
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        environment:
            - OPENAI_API_KEY=$OPENAI_API_KEY
            - X_SERVER_URL=https://api.red-pill.ai/v1
            - SOL_ADDRESS=So11111111111111111111111111111111111111112
            - SLIPPAGE=1
            - RPC_URL=https://api.mainnet-beta.solana.com
            - SERVER_PORT=3000
        ports:
            - "33011:3000"
        restart: always

volumes:
    tee:
